export const GET_FORMS_SUCCESS = "GET_FORMS_SUCCESS";
export const GET_FORMS_FAILED = "GET_FORMS_SUCCESS";
export const GET_FORMS_PENDING = "GET_FORMS_PENDING";

export const SUBMIT_FORM_SUCCESS = "SUBMIT_FORM_SUCCESS";
export const SUBMIT_FORM_FAILED = "SUBMIT_FORM_SUCCESS";
export const SUBMIT_FORM_PENDING = "SUBMIT_FORM_PENDING";

export const SELECT_FORM_TYPE = "SELECT_FORM_TYPE";
export const CHOOSE_FILE = "CHOOSE_FILE";
export const SET_FORM_NAME = "SET_FORM_NAME";
export const SET_FILE_ID = "SET_FILE_ID";
export const FILTER_BY_FOLDER = "FILTER_BY_FOLDER";

export const GEN_REPORT_SUCCESS = "GEN_REPORT_SUCCESS";
export const GEN_REPORT_FAILED = "GEN_REPORT_FAILED";
export const GEN_REPORT_PENDING = "GEN_REPORT_PENDING";